def obj() : return lambda : None

STATUS_CODES = obj()

STATUS_CODES.OK = 200
STATUS_CODES.NOT_FOUND = 404
STATUS_CODES.LOCKED = 423
STATUS_CODES.DUPLICATE = 409
STATUS_CODES.PERMISSION_DENIED = 403
STATUS_CODES.API_PROBLEM = 500
STATUS_CODES.VALIDATION_ERROR = 400
STATUS_CODES.SMS_PROBLEM = 515
STATUS_CODES.NOTIFICATION_PROBLEM = 516
STATUS_CODES.PAYMENT_PROBLEM = 517

